import {
  CommercialOffer,
  Cooperative,
  Farmer,
  IotNode,
  IotReading,
  NdviSnapshot,
  Parcelle,
  InsuranceApplication,
  InsuranceClaim,
  InsuranceFieldAudit,
  InsuranceMission,
  InsurancePolicy,
  MonitoringAlert,
  RaxEvaluation,
  WakamaAlert,
} from "@/types";

export const farmers: Farmer[] = [
  {
    id: "far_001",
    fullName: "Youssef El Amrani",
    nationalIdMasked: "BE******41",
    phone: "+212600112233",
    region: "Meknès",
    primaryCrop: "Blé tendre",
    totalAreaHa: 18,
    source: "SEED_DEMO",
  },
  {
    id: "far_002",
    fullName: "Fatima Zahra B.",
    nationalIdMasked: "CD******89",
    phone: "+212611223344",
    region: "Khénifra",
    primaryCrop: "Olivier",
    totalAreaHa: 27,
    source: "SEED_DEMO",
  },
  {
    id: "far_003",
    fullName: "Abdelkader Laabi",
    nationalIdMasked: "EE******67",
    phone: "+212622334455",
    region: "Béni Mellal",
    primaryCrop: "Maïs",
    totalAreaHa: 12,
    source: "SEED_DEMO",
  },
];

export const cooperatives: Cooperative[] = [
  {
    id: "coop_001",
    name: "Coop Atlas Vert",
    region: "Fès-Meknès",
    filiere: "Cereales",
    memberCount: 42,
    aggregatedAreaHa: 340,
    contactName: "Nadia Ait Hamou",
    source: "SEED_DEMO",
  },
  {
    id: "coop_002",
    name: "Coop Rhamna Résilience",
    region: "Marrakech-Safi",
    filiere: "Olivier",
    memberCount: 28,
    aggregatedAreaHa: 210,
    contactName: "Karim Tazi",
    source: "SEED_DEMO",
  },
];

export const parcelles: Parcelle[] = [
  {
    id: "par_001",
    farmerId: "far_001",
    cooperativeId: "coop_001",
    name: "Parcelle Atlas Nord",
    culture: "Ble tendre",
    superficie: 6.2,
    areaHa: 6.2,
    lat: 33.916,
    lng: -5.546,
    polygone: "poly_par_001",
    ndvi: 0.63,
    status: "ACTIVE",
    source: "SEED_DEMO",
  },
  {
    id: "par_002",
    farmerId: "far_002",
    cooperativeId: "coop_002",
    name: "Parcelle Rhamna Est",
    culture: "Olivier",
    superficie: 8.8,
    areaHa: 8.8,
    lat: 32.145,
    lng: -7.989,
    polygone: "poly_par_002",
    ndvi: 0.48,
    status: "WATCH",
    source: "SEED_DEMO",
  },
  {
    id: "par_003",
    farmerId: "far_003",
    cooperativeId: "coop_002",
    name: "Parcelle Beni Mellal Sud",
    culture: "Mais",
    superficie: 4.5,
    areaHa: 4.5,
    lat: 32.331,
    lng: -6.356,
    polygone: "poly_par_003",
    ndvi: 0.59,
    status: "ACTIVE",
    source: "SEED_DEMO",
  },
];

export const wakamaAlerts: WakamaAlert[] = [
  {
    id: "wal_001",
    farmerId: "far_001",
    cooperativeId: "coop_001",
    parcelleId: "par_001",
    type: "NDVI",
    severity: "INFO",
    title: "Variation vegetative legere",
    message: "Baisse NDVI legere observee sur 7 jours.",
    read: false,
    createdAt: "2026-05-24",
    source: "SEED_DEMO",
  },
  {
    id: "wal_002",
    farmerId: "far_002",
    cooperativeId: "coop_002",
    parcelleId: "par_002",
    type: "WEATHER",
    severity: "WARNING",
    title: "Deficit de pluie",
    message: "Pluviometrie inferieure au seuil saisonnier.",
    read: false,
    createdAt: "2026-05-27",
    source: "SEED_DEMO",
  },
  {
    id: "wal_003",
    farmerId: "far_002",
    cooperativeId: "coop_002",
    parcelleId: "par_002",
    type: "FIELD",
    severity: "CRITICAL",
    title: "Stress severe confirme terrain",
    message: "Anomalie severe a verifier avec agent terrain.",
    read: false,
    createdAt: "2026-05-28",
    source: "SEED_DEMO",
  },
];

export const ndviSnapshots: NdviSnapshot[] = [
  {
    parcelleId: "par_001",
    ndvi: 0.63,
    capturedAt: "2026-05-24",
    provider: "SEED",
    source: "SEED_DEMO",
  },
  {
    parcelleId: "par_002",
    ndvi: 0.48,
    capturedAt: "2026-05-27",
    provider: "SEED",
    source: "SEED_DEMO",
  },
  {
    parcelleId: "par_003",
    ndvi: 0.59,
    capturedAt: "2026-05-26",
    provider: "SEED",
    source: "SEED_DEMO",
  },
];

export const iotNodes: IotNode[] = [
  {
    id: "iot_001",
    cooperativeId: "coop_002",
    farmerId: "far_002",
    name: "Node Rhamna 01",
    status: "ONLINE",
    lat: 32.147,
    lng: -7.992,
    lastSeenAt: "2026-05-28T09:20:00Z",
    source: "SEED_DEMO",
  },
];

export const iotReadings: IotReading[] = [
  {
    id: "read_001",
    nodeId: "iot_001",
    temperatureAir: 31.4,
    humidityAir: 29.8,
    soilMoisture: 18.2,
    soilTemperature: 27.1,
    capturedAt: "2026-05-28T09:00:00Z",
    source: "SEED_DEMO",
  },
  {
    id: "read_002",
    nodeId: "iot_001",
    temperatureAir: 32.2,
    humidityAir: 27.1,
    soilMoisture: 17.6,
    soilTemperature: 27.9,
    capturedAt: "2026-05-28T12:00:00Z",
    source: "SEED_DEMO",
  },
];

export const applications: InsuranceApplication[] = [
  {
    id: "app_001",
    reference: "APP-MA-0001",
    farmerId: "far_001",
    cooperativeId: "coop_001",
    insurerName: "Assureur Partenaire A",
    cropType: "Blé tendre",
    areaHa: 15,
    requestedCoverageMad: 250000,
    status: "UNDER_REVIEW",
    riskTier: "MEDIUM_RISK",
    createdAt: "2026-05-10",
    source: "SEED_DEMO",
  },
  {
    id: "app_002",
    reference: "APP-MA-0002",
    farmerId: "far_002",
    insurerName: "Assureur Partenaire B",
    cropType: "Olivier",
    areaHa: 21,
    requestedCoverageMad: 390000,
    status: "REQUIRES_FIELD_AUDIT",
    riskTier: "HIGH_RISK",
    createdAt: "2026-05-13",
    source: "SEED_DEMO",
  },
  {
    id: "app_003",
    reference: "APP-MA-0003",
    farmerId: "far_003",
    cooperativeId: "coop_002",
    insurerName: "Assureur Partenaire A",
    cropType: "Maïs",
    areaHa: 9,
    requestedCoverageMad: 180000,
    status: "PRICED",
    riskTier: "LOW_RISK",
    createdAt: "2026-05-19",
    source: "SEED_DEMO",
  },
];

export const missions: InsuranceMission[] = [
  {
    id: "mis_001",
    applicationId: "app_001",
    missionType: "SATELLITE_REVIEW",
    assignedTo: "Équipe Télédétection",
    scheduledFor: "2026-05-22",
    status: "DONE",
    region: "Meknès",
    source: "SEED_DEMO",
  },
  {
    id: "mis_002",
    applicationId: "app_002",
    missionType: "FIELD_VISIT",
    assignedTo: "Inspecteur Idriss",
    scheduledFor: "2026-05-29",
    status: "PLANNED",
    region: "Khénifra",
    source: "SEED_DEMO",
  },
  {
    id: "mis_003",
    applicationId: "app_003",
    missionType: "PHONE_VERIFICATION",
    assignedTo: "Backoffice Casanearshore",
    scheduledFor: "2026-05-27",
    status: "IN_PROGRESS",
    region: "Béni Mellal",
    source: "SEED_DEMO",
  },
];

export const fieldAudits: InsuranceFieldAudit[] = [
  {
    id: "aud_001",
    applicationId: "app_001",
    missionId: "mis_001",
    farmerId: "far_001",
    declaredAreaHa: 15,
    measuredAreaHa: 14.7,
    areaDeltaPercent: -2,
    declaredPolygon: "poly_declared_aud_001",
    measuredPolygon: "poly_measured_aud_001",
    assetsApprovedCount: 4,
    assetsRejectedCount: 0,
    integrityHash: "sha256:aud001-integrity",
    auditMode: "WEB_DEMO",
    status: "COMPLETED",
    createdAt: "2026-05-21",
    vegetationScore: 73,
    irrigationType: "GOUTTE_A_GOUTTE",
    anomalyDetected: false,
    notes: "Couverture végétale cohérente avec la saison.",
    completedAt: "2026-05-22",
    source: "SEED_DEMO",
  },
  {
    id: "aud_002",
    applicationId: "app_003",
    missionId: "mis_003",
    farmerId: "far_003",
    declaredAreaHa: 9,
    measuredAreaHa: 8.4,
    areaDeltaPercent: -6.7,
    declaredPolygon: "poly_declared_aud_002",
    measuredPolygon: "poly_measured_aud_002",
    assetsApprovedCount: 3,
    assetsRejectedCount: 1,
    integrityHash: "sha256:aud002-integrity",
    auditMode: "WEB_DEMO",
    status: "COMPLETED",
    createdAt: "2026-05-26",
    vegetationScore: 62,
    irrigationType: "PLUVIAL",
    anomalyDetected: true,
    notes: "Écart d'humidité observé sur la parcelle nord.",
    completedAt: "2026-05-27",
    source: "SEED_DEMO",
  },
];

export const raxEvaluations: RaxEvaluation[] = [
  {
    id: "rax_001",
    applicationId: "app_001",
    gravity: 3.4,
    frequency: 3.8,
    detection: 0.9,
    raxBrut: 11.6,
    wrsScore: 46.4,
    raxScore: 11.6,
    riskTier: "MEDIUM_RISK",
    recommendation: "Recommandation non décisionnelle: audit terrain léger.",
    source: "SEED_DEMO",
  },
  {
    id: "rax_002",
    applicationId: "app_002",
    gravity: 4.2,
    frequency: 4.1,
    detection: 0.9,
    raxBrut: 15.5,
    wrsScore: 62,
    raxScore: 15.5,
    riskTier: "HIGH_RISK",
    recommendation:
      "Recommandation non décisionnelle: majoration technique et revue humaine.",
    source: "SEED_DEMO",
  },
];

export const pricingOffers: CommercialOffer[] = [
  {
    id: "off_001",
    applicationId: "app_001",
    raxEvaluationId: "rax_001",
    insurerName: "Assureur Partenaire A",
    totalInsuredCapital: 250000,
    purePremiumAmount: 18500,
    managementFees: 1800,
    taxRateApplied: 0.1,
    taxAmount: 2030,
    totalCommercialPremiumTtc: 22330,
    farmerDecision: "PENDING",
    generatedAt: "2026-05-26",
    expiresAt: "2026-06-10",
    shortUrlToken: "WK-PRC-001",
    agencyPickupToken: "GHT-001-26",
    technicalPremiumMad: 18500,
    suggestedCommercialPremiumMad: 22330,
    deductiblePct: 10,
    status: "PENDING_FARMER",
    source: "SEED_DEMO",
  },
  {
    id: "off_002",
    applicationId: "app_003",
    insurerName: "Assureur Partenaire A",
    totalInsuredCapital: 180000,
    purePremiumAmount: 12800,
    managementFees: 900,
    taxRateApplied: 0.1,
    taxAmount: 1370,
    totalCommercialPremiumTtc: 15070,
    farmerDecision: "ACCEPTED",
    farmerDecisionAt: "2026-05-28",
    generatedAt: "2026-05-21",
    expiresAt: "2026-06-04",
    shortUrlToken: "WK-PRC-002",
    agencyPickupToken: "GHT-002-26",
    technicalPremiumMad: 12800,
    suggestedCommercialPremiumMad: 15070,
    deductiblePct: 8,
    status: "FARMER_ACCEPTED",
    source: "SEED_DEMO",
  },
];

export const policies: InsurancePolicy[] = [
  {
    id: "pol_001",
    offerId: "off_002",
    farmerId: "far_003",
    policyNumber: "POL-A-2026-00089",
    applicationId: "app_003",
    insurerName: "Assureur Partenaire A",
    totalInsuredCapital: 180000,
    totalPremiumTtc: 15070,
    coverageStartDate: "2026-05-21",
    coverageEndDate: "2026-06-20",
    issuedAt: "2026-05-21",
    coverageMad: 180000,
    annualPremiumMad: 15070,
    effectiveDate: "2026-05-21",
    expiryDate: "2026-06-20",
    status: "ACTIVE",
    source: "SEED_DEMO",
  },
  {
    id: "pol_002",
    policyNumber: "POL-B-2026-00124",
    applicationId: "app_002",
    farmerId: "far_002",
    insurerName: "Assureur Partenaire B",
    totalInsuredCapital: 390000,
    totalPremiumTtc: 30200,
    coverageStartDate: "2026-05-18",
    coverageEndDate: "2026-07-30",
    issuedAt: "2026-05-18",
    coverageMad: 390000,
    annualPremiumMad: 30200,
    effectiveDate: "2026-05-18",
    expiryDate: "2026-07-30",
    status: "CLAIM_OPEN",
    source: "SEED_DEMO",
  },
];

export const monitoringAlerts: MonitoringAlert[] = [
  {
    id: "alr_001",
    policyId: "pol_001",
    applicationId: "app_003",
    farmerId: "far_003",
    type: "NDVI",
    severity: "WARNING",
    status: "OPEN",
    message: "Stress hydrique detecte au-dessus du seuil hebdomadaire.",
    level: "WARNING",
    title: "Stress hydrique détecté > seuil hebdomadaire",
    createdAt: "2026-05-24",
    resolved: false,
    source: "SEED_DEMO",
  },
  {
    id: "alr_002",
    policyId: "pol_001",
    applicationId: "app_003",
    farmerId: "far_003",
    type: "WEATHER",
    severity: "INFO",
    status: "RESOLVED",
    message: "Synchronisation meteo completee.",
    level: "INFO",
    title: "Synchronisation météo complétée",
    createdAt: "2026-05-26",
    resolved: true,
    source: "SEED_DEMO",
  },
  {
    id: "alr_003",
    policyId: "pol_002",
    applicationId: "app_002",
    farmerId: "far_002",
    type: "FIELD",
    severity: "CRITICAL",
    status: "OPEN",
    message: "Anomalie terrain critique: perte de biomasse et stress severe.",
    level: "CRITICAL",
    title: "Anomalie terrain critique",
    createdAt: "2026-05-28",
    resolved: false,
    source: "SEED_DEMO",
  },
];

export const claims: InsuranceClaim[] = [
  {
    id: "clm_001",
    claimNumber: "CLM-2026-0041",
    policyId: "pol_001",
    applicationId: "app_003",
    farmerId: "far_003",
    monitoringAlertId: "alr_001",
    severity: "WARNING",
    estimatedAmount: 42000,
    description: "Signalement secheresse suite a baisse NDVI et stress hydrique.",
    createdAt: "2026-05-25",
    updatedAt: "2026-05-27",
    claimType: "DROUGHT",
    estimatedLossMad: 42000,
    status: "UNDER_REVIEW",
    source: "SEED_DEMO",
  },
  {
    id: "clm_002",
    claimNumber: "CLM-2026-0050",
    policyId: "pol_002",
    applicationId: "app_002",
    farmerId: "far_002",
    monitoringAlertId: "alr_003",
    severity: "CRITICAL",
    estimatedAmount: 91000,
    description: "Signalement critique apres anomalie terrain severe.",
    createdAt: "2026-05-28",
    updatedAt: "2026-05-28",
    claimType: "OTHER",
    estimatedLossMad: 91000,
    status: "DECLARED",
    source: "SEED_DEMO",
  },
  {
    id: "clm_003",
    claimNumber: "CLM-2026-0032",
    policyId: "pol_001",
    applicationId: "app_003",
    farmerId: "far_003",
    severity: "INFO",
    estimatedAmount: 18000,
    description: "Dossier historique cloture apres revue assureur.",
    createdAt: "2026-05-10",
    updatedAt: "2026-05-18",
    claimType: "PEST",
    estimatedLossMad: 18000,
    status: "CLOSED",
    source: "SEED_DEMO",
  },
];
