import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-plex-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-space-grotesk)", "var(--font-plex-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        brand: {
          violet: "rgb(var(--brand-violet) / <alpha-value>)",
          green: "rgb(var(--brand-green) / <alpha-value>)",
          ochre: "rgb(var(--brand-ochre) / <alpha-value>)",
          bg: "rgb(var(--app-bg) / <alpha-value>)",
          bgSoft: "rgb(var(--app-bg-soft) / <alpha-value>)",
          surface: "rgb(var(--app-surface) / <alpha-value>)",
          surfaceRaised: "rgb(var(--app-surface-muted) / <alpha-value>)",
          border: "rgb(var(--app-border) / <alpha-value>)",
          textMuted: "rgb(var(--app-text-muted) / <alpha-value>)",
          dim: "rgb(var(--app-dim) / <alpha-value>)",
          success: "rgb(var(--app-success) / <alpha-value>)",
          warning: "rgb(var(--app-warning) / <alpha-value>)",
          danger: "rgb(var(--app-danger) / <alpha-value>)",
          info: "rgb(var(--app-info) / <alpha-value>)",
        },
        wk: {
          bg: "var(--wk-bg)",
          surface: "var(--wk-surface)",
          surface2: "var(--wk-surface-2)",
          surface3: "var(--wk-surface-3)",
          border: "var(--wk-border)",
          border2: "var(--wk-border-2)",
          text: "var(--wk-text)",
          muted: "var(--wk-muted)",
          faint: "var(--wk-faint)",
          primary: "var(--wk-primary)",
          primaryInk: "var(--wk-primary-ink)",
          primarySoft: "var(--wk-primary-soft)",
          teal: "var(--wk-teal)",
          tealInk: "var(--wk-teal-ink)",
          tealSoft: "var(--wk-teal-soft)",
          violet: "var(--wk-violet)",
          violetInk: "var(--wk-violet-ink)",
          violetSoft: "var(--wk-violet-soft)",
          amber: "var(--wk-amber)",
          amberInk: "var(--wk-amber-ink)",
          amberSoft: "var(--wk-amber-soft)",
          coral: "var(--wk-coral)",
          coralInk: "var(--wk-coral-ink)",
          coralSoft: "var(--wk-coral-soft)",
          live: "var(--wk-live)",
          liveInk: "var(--wk-live-ink)",
          liveSoft: "var(--wk-live-soft)",
          canvasBg: "var(--wk-canvas-bg)",
          canvasSurface: "var(--wk-canvas-surface)",
          canvasSurface2: "var(--wk-canvas-surface-2)",
          canvasBorder: "var(--wk-canvas-border)",
          canvasText: "var(--wk-canvas-text)",
          canvasMuted: "var(--wk-canvas-muted)",
          canvasFaint: "var(--wk-canvas-faint)",
        },
      },
      boxShadow: {
        premium: "0 14px 28px rgba(15, 23, 42, 0.08)",
        "premium-dark": "0 14px 28px rgba(0, 0, 0, 0.35)",
        "wk-sm": "var(--wk-shadow-sm)",
        wk: "var(--wk-shadow)",
        "wk-lg": "var(--wk-shadow-lg)",
      },
    },
  },
  plugins: [],
};

export default config;
